bases:
  - ../../base

namespace: prod

namePrefix: prod-

# patchesStrategicMerge:
#   - replicas.yaml
#   - ports.yaml

configMapGenerator:
- envs:
  - config.properties
  name: transaction-config

labels:
- includeSelectors: true
  pairs:
    app: prod-transaction-service

images:
- name: mohamedsamir170/transaction-service
  newTag: prod