bases:
  - ../../base

namespace: dev

namePrefix: dev-

patchesStrategicMerge:
  - replicas.yaml
  - ports.yaml

configMapGenerator:
- envs:
  - config.properties
  name: user-config
labels:
- includeSelectors: true
  pairs:
    app: dev-user-service
images:
- name: mohamedsamir170/user-service
  newTag: dev