bases:
  - ../../base

namespace: prod

namePrefix: prod-

# patchesStrategicMerge:
#   - replicas.yaml
#   - ports.yaml

configMapGenerator:
- envs:
  - config.properties
  name: insta-pay-config

labels:
- includeSelectors: true
  pairs:
    app: prod-insta-front

images:
- name: mohamedsamir170/insta-front
  newTag: latest